version: '3.4'
services:
  db:
    image: joses166/mysql-rest-with-spring-boot-udemy
    command: mysqld --default-authentication-plugin=mysql_native_password # comando para iniciar bd
    restart: always
    build:
      context: . # local do arquivo, caso esteja na mesma pasta
      dockerfile: Dockerfile # nome do arquivo
    environment: 
      TZ: America/Sao_Paulo # timezone banco
      MYSQL_ROOT_PASSWORD: docker # senha usuario root bd
      MYSQL_USER: docker # usuario bd
      MYSQL_PASSWORD: docker # senha bd
      MYSQL_DATABASE: rest_with_spring_boot_udemy # nome do banco
    ports:
      - "3308:3306" # porta que será exposta / porta local
    networks:
      - udemy-network
  rest-with-spring-boot-udemy:
    image: joses166/rest-with-spring-boot-udemy 
    restart: always
    build: ./RestWithSpringBootUdemy_Docker
    working_dir: /RestWithSpringBootUdemy_Docker
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./RestWithSpringBootUdemy_Docker:/RestWithSpringBootUdemy_Docker
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run # comando para iniciar aplicação
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge